AWSTemplateFormatVersion: '2010-09-09'
Description: 'Shift-Left Security Demo - Intentionally Vulnerable Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: demo
    Description: Environment name for resource tagging

Resources:
  # SECURITY ISSUE 1: S3 Bucket with multiple misconfigurations
  VulnerableBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'shift-left-demo-bucket-${AWS::AccountId}-${AWS::Region}'
      # SECURITY ISSUE: No versioning enabled (data loss risk)
      # VersioningConfiguration:
      #   Status: Enabled

      # SECURITY ISSUE: No server-side encryption configured
      # BucketEncryption:
      #   ServerSideEncryptionConfiguration:
      #     - ServerSideEncryptionByDefault:
      #         SSEAlgorithm: AES256

      # SECURITY ISSUE: Public access allowed
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false          # Should be true
        BlockPublicPolicy: false        # Should be true
        IgnorePublicAcls: false        # Should be true
        RestrictPublicBuckets: false   # Should be true

      # SECURITY ISSUE: No access logging configured
      # LoggingConfiguration:
      #   DestinationBucketName: !Ref LoggingBucket
      #   LogFilePrefix: access-logs/

      Tags:
        - Key: Name
          Value: VulnerableS3Bucket
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: ShiftLeftSecurityDemo
        - Key: SecurityRisk
          Value: High

  # SECURITY ISSUE 2: Bucket policy allowing public access
  VulnerableBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VulnerableBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # SECURITY ISSUE: Public read access
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'              # DANGEROUS: Public access
            Action: 's3:GetObject'
            Resource: !Sub '${VulnerableBucket}/*'

          # SECURITY ISSUE: Public list access
          - Sid: PublicListBucket
            Effect: Allow
            Principal: '*'              # DANGEROUS: Public access
            Action: 's3:ListBucket'
            Resource: !Ref VulnerableBucket

          # SECURITY ISSUE: Public write access (extremely dangerous)
          - Sid: PublicWriteAccess
            Effect: Allow
            Principal: '*'              # DANGEROUS: Anyone can write
            Action:
              - 's3:PutObject'
              - 's3:PutObjectAcl'
              - 's3:DeleteObject'
            Resource: !Sub '${VulnerableBucket}/*'

  # SECURITY ISSUE 3: IAM Role with excessive permissions
  VulnerableIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'VulnerableDemoRole-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
            # SECURITY ISSUE: No condition restrictions
            # Condition:
            #   StringEquals:
            #     'aws:RequestedRegion': !Ref AWS::Region

      # SECURITY ISSUE: No managed policies path restriction
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess  # Too broad

      Tags:
        - Key: Name
          Value: VulnerableIAMRole
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: ShiftLeftSecurityDemo
        - Key: SecurityRisk
          Value: Critical

  # SECURITY ISSUE 4: IAM Policy with wildcard permissions
  VulnerableIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: VulnerableDemoPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # SECURITY ISSUE: Wildcard permissions on all resources
          - Sid: DangerousWildcardAccess
            Effect: Allow
            Action: '*'                 # DANGEROUS: All actions
            Resource: '*'               # DANGEROUS: All resources

          # SECURITY ISSUE: Admin access without conditions
          - Sid: UnrestrictedAdminAccess
            Effect: Allow
            Action:
              - 'iam:*'
              - 's3:*'
              - 'ec2:*'
              - 'rds:*'
              - 'lambda:*'
            Resource: '*'
            # Missing condition restrictions like:
            # Condition:
            #   StringEquals:
            #     'aws:RequestedRegion': !Ref AWS::Region

      Roles:
        - !Ref VulnerableIAMRole

  # SECURITY ISSUE 5: IAM User with programmatic access (no MFA)
  VulnerableIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub 'demo-user-${AWS::Region}'
      # SECURITY ISSUE: No MFA requirement for this user
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - !Ref VulnerableIAMPolicyForUser
      Tags:
        - Key: Name
          Value: VulnerableIAMUser
        - Key: Environment
          Value: !Ref Environment
        - Key: SecurityRisk
          Value: Medium

  # Additional vulnerable IAM policy for user
  VulnerableIAMPolicyForUser:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'VulnerableUserPolicy-${AWS::Region}'
      Description: 'Intentionally overprivileged policy for demo user'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # SECURITY ISSUE: Broad S3 access
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource: '*'               # Should be restricted to specific buckets

  # SECURITY ISSUE 6: Access keys for programmatic access (should use roles)
  VulnerableAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref VulnerableIAMUser
      Status: Active
      # SECURITY ISSUE: Access keys are less secure than IAM roles

Outputs:
  BucketName:
    Description: 'Name of the vulnerable S3 bucket'
    Value: !Ref VulnerableBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  BucketArn:
    Description: 'ARN of the vulnerable S3 bucket'
    Value: !GetAtt VulnerableBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'

  IAMRoleArn:
    Description: 'ARN of the vulnerable IAM role'
    Value: !GetAtt VulnerableIAMRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-IAMRoleArn'

  AccessKeyId:
    Description: 'Access Key ID for vulnerable user (demo purposes only)'
    Value: !Ref VulnerableAccessKey
    # SECURITY ISSUE: Outputting sensitive information

  SecurityIssuesCount:
    Description: 'Number of intentional security issues in this template'
    Value: '6+'
    Export:
      Name: !Sub '${AWS::StackName}-SecurityIssuesCount'